"""Add RunningLog model

Revision ID: a36ab4c1439b
Revises: 602a38124879
Create Date: 2025-01-08 11:44:51.994874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36ab4c1439b'
down_revision: Union[str, None] = '602a38124879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('running_log',
        sa.Column('log_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('km', sa.Float(), nullable=True),
        sa.Column('date_added', sa.Date(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('chat_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_running_log_log_id'), 'running_log', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_running_log_log_id'), table_name='running_log')
    op.drop_table('running_log')
    # ### end Alembic commands ###
