"""Add yearly stats to users

Revision ID: add_yearly_stats_to_users
Create Date: 2025-01-10 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_yearly_stats_to_users'
down_revision: Union[str, None] = 'd5f052754e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yearly_goal', sa.REAL(), nullable=True))
    op.add_column('users', sa.Column('yearly_progress', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'yearly_progress')
    op.drop_column('users', 'yearly_goal')
    # ### end Alembic commands ### 